# -*- coding: utf-8 -*-
"""ArtfusionNet.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LTPyXvU6hpG9Nu3h9hmFxyiJa9fkxA0N
"""

# models/artfusionnet.py

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision.models import efficientnet_v2_s, EfficientNet_V2_S_Weights


class PSABlock(nn.Module):
    """
    Polarized Self-Attention block.
    Applies both channel and spatial attention to refine feature maps.
    """
    def __init__(self, in_channels):
        super().__init__()

        # --- Channel attention branch ---
        # asks: which feature channels are most important?
        self.ch_wv = nn.Conv2d(in_channels, in_channels // 2, kernel_size=1)
        self.ch_wq = nn.Conv2d(in_channels, 1, kernel_size=1)
        self.ch_softmax = nn.Softmax(dim=2)
        self.ch_wz = nn.Conv2d(in_channels // 2, in_channels, kernel_size=1)
        self.ln = nn.LayerNorm(in_channels)
        self.sigmoid = nn.Sigmoid()

        # --- Spatial attention branch ---
        # asks: which spatial locations are most important?
        self.sp_wv = nn.Conv2d(in_channels, in_channels // 2, kernel_size=1)
        self.sp_wq = nn.Conv2d(in_channels, in_channels // 2, kernel_size=1)
        self.sp_softmax = nn.Softmax(dim=-1)
        self.agp = nn.AdaptiveAvgPool2d((1, 1))

    def forward(self, x):
        B, C, H, W = x.shape  # batch, channels, height, width

        # --- Channel attention ---
        # wv: value projection  shape: (B, C/2, H, W)
        ch_wv = self.ch_wv(x)
        # wq: query projection  shape: (B, 1, H, W) → (B, 1, H*W)
        ch_wq = self.ch_wq(x).reshape(B, 1, H * W)
        ch_wq = self.ch_softmax(ch_wq)
        # multiply query × value to get channel context
        # (B, C/2, H, W) → (B, C/2, H*W) × (B, H*W, 1) → (B, C/2, 1)
        ch_wv = ch_wv.reshape(B, C // 2, H * W)
        ch_attn = torch.bmm(ch_wv, ch_wq.transpose(1, 2))  # (B, C/2, 1)
        ch_attn = ch_attn.reshape(B, C // 2, 1, 1)
        ch_attn = self.ch_wz(ch_attn)                       # (B, C, 1, 1)
        # layer norm + sigmoid to get attention weights 0–1
        ch_attn = self.ln(ch_attn.reshape(B, C)).reshape(B, C, 1, 1)
        ch_attn = self.sigmoid(ch_attn)
        # apply channel attention to input
        ch_out = ch_attn * x

        # --- Spatial attention ---
        # wv and wq projections
        sp_wv = self.sp_wv(x)                               # (B, C/2, H, W)
        sp_wq = self.sp_wq(x)                               # (B, C/2, H, W)
        # pool wq to (B, C/2, 1, 1) → (B, 1, C/2)
        sp_wq = self.agp(sp_wq).reshape(B, 1, C // 2)
        sp_wq = self.sp_softmax(sp_wq)
        # (B, C/2, H*W) × (B, C/2, 1) → spatial map (B, 1, H*W)
        sp_wv = sp_wv.reshape(B, C // 2, H * W)
        sp_attn = torch.bmm(sp_wq, sp_wv)                   # (B, 1, H*W)
        sp_attn = self.sigmoid(sp_attn.reshape(B, 1, H, W)) # (B, 1, H, W)
        # apply spatial attention to input
        sp_out = sp_attn * x

        # --- Fuse both branches ---
        return ch_out + sp_out


class ArtFusionNet(nn.Module):
    def __init__(self, num_classes, hidden_dim=512, dropout=0.4):
        super().__init__()

        # Load pretrained EfficientNetV2-S backbone
        backbone = efficientnet_v2_s(weights=EfficientNet_V2_S_Weights.IMAGENET1K_V1)

        # Freeze early layers, unfreeze last block
        for param in backbone.parameters():
            param.requires_grad = False
        for param in backbone.features[-1].parameters():
            param.requires_grad = True

        # Remove the classifier — keep the feature extractor
        # EfficientNetV2-S features output shape: (B, 1280, 7, 7) for 224x224 input
        self.backbone_features = backbone.features  # spatial feature maps
        self.backbone_pool = backbone.avgpool        # global average pool

        # PSA attention applied BEFORE pooling (while spatial info still exists)
        self.psa = PSABlock(in_channels=1280)

        # MLP classification head
        self.head = nn.Sequential(
            nn.Linear(1280, hidden_dim),   # 1280 → 512
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, num_classes)  # 512 → 27
        )

    def forward(self, x):
        # Step 1: extract spatial feature maps (B, 1280, 7, 7)
        features = self.backbone_features(x)

        # Step 2: apply PSA attention — refine WHAT and WHERE to focus
        features = self.psa(features)

        # Step 3: global average pool → (B, 1280, 1, 1) → (B, 1280)
        features = self.backbone_pool(features)
        features = torch.flatten(features, 1)

        # Step 4: classify
        output = self.head(features)
        return output